services:
  - type: web
    name: backend-libros
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
    autoDeploy: true
